name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y libglib2.0-bin zip gettext

      - name: Build Package
        run: make package

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Resource_Monitor
          path: build/Resource_Monitor@Ory0n.zip

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: build/Resource_Monitor@Ory0n.zip
